name: DreamAlert
version: 1.1.0
api: [1.12.0]
author: Dreamcrafters
main: DreamAlert\MainClass

commands:
  adminjoin:
    description: "DreamAlert main command"
    usage: "/DreamAlert <message on op entry>"
    permission: "DreamAlert.command.adminjoin"

permissions:
  DreamAlert:
    default: op
    description: "Allows ops to use the DreamAlert command"
    children:
      alias.command:
        default: op
        description: "Allows ops to use the DreamAlert command"
        children:
          alias.command.alias:
            default: op
            description: "Allows changing of the join message"

